version: '2'
services:
  
  prometheus:
    image: prom/prometheus:0.18.0
    volumes:
        - ./monitoring-config/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
    command:
        - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'
      
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD='pass'
    depends_on:
      - prometheus
    ports:
          - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

                
volumes:
  prometheus_data: {}
  grafana_data: {}
